<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" retried="1" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="example suite 1" duration-ms="52" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
    <groups>
    </groups>
    <test name="Regression suite 1" duration-ms="52" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
      <class name="TestMethods">
        <test-method status="PASS" signature="test1()[pri:0, instance:TestMethods@3c09711b]" name="test1" duration-ms="13" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:TestMethods@3c09711b]" name="test3" duration-ms="1" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:TestMethods@3c09711b]" name="test2" duration-ms="0" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test4()[pri:0, instance:TestMethods@3c09711b]" name="test4" duration-ms="2" retried="true" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [2]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestMethods.test4(TestMethods.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="test4()[pri:0, instance:TestMethods@3c09711b]" name="test4" duration-ms="0" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="test5()[pri:0, instance:TestMethods@3c09711b]" name="test5" duration-ms="0" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="after()[pri:0, instance:TestMethods@3c09711b]" name="after" is-config="true" duration-ms="1" started-at="2020-05-10T11:30:47 IST" finished-at="2020-05-10T11:30:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- TestMethods -->
    </test> <!-- Regression suite 1 -->
  </suite> <!-- example suite 1 -->
</testng-results>
